using System.Collections;
using System.Collections.Generic;
using System.Text;
using UnityEngine;

namespace Starlight.Words
{
    [System.Serializable]
    public class CardData
    {
	   private List<WordData> words;

	   //TODO: needs to be generated by GPT
	   public Sprite Icon { get; private set; }

	   //TODO: needs to be generated by GPT
	   public string Description { get; private set; }

	   public CardData()
	   {
		  words = new();
		  //TODO: Generate AI sprite, AI description!
	   }

	   public void AppendWord(WordData data)
	   {
		  words.Add(data);
	   }

	   public string GetPrompt()
	   {
		  string promptBuilder = "";
		  foreach (var word in words)
		  {
			 promptBuilder += word.word + " ";
		  }
		  return promptBuilder;
	   }

	   public override string ToString() => GetPrompt();
    }
}